enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "dev"

[YouTube-Extended]
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "module"
version = "20.21.37"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Change form factor' 'Swipe controls' 'Translations for YouTube'"
included-patches = "'Theme'"

[YouTube-Music-Extended]
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "arm64-v8a"
version = "8.30.54"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
excluded-patches = "'Bypass image region restrictions' 'Translations for YouTube Music'"
